spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/seoulmate
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/test-client/callback"
            scope:
              - email
              - profile

server:
  port: 8080
  servlet:
    context-path: /

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:supersecretkeysupersecretkeysupersecretkeysupersecretkey}
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 2592000000  # 30 days in milliseconds

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  show-actuator: false

# Google Maps API Configuration
google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}  # Set via environment variable

# Scraper Configuration
scraper:
  scheduler:
    enabled: true  # 스케줄러 활성화 여부
    cron: "0 0 0 * * SUN"  # 매주 일요일 자정에 실행
