spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/seoulmate
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/test-client/callback"
            scope:
              - email
              - profile

server:
  port: 8080
  servlet:
    context-path: /

# Authentication Configuration
jwt:
  secret: ${JWT_SECRET:supersecretkeysupersecretkeysupersecretkeysupersecretkey}
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 2592000000  # 30 days in milliseconds

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  show-actuator: false

# External Services
google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

# Application Features
scraper:
  scheduler:
    enabled: true
    cron: "0 0 0 * * SUN"  # Every Sunday at midnight
